name: Notify workflow failure
author: Shunsuke Suzuki
# branding:
#   icon: check
#   color: yellow
description: |
  Notify the failure of GitHub Actions Workflow to a GitHub Issue.
inputs:
  issue_number:
    description: GitHub Issue number to notify the result
    required: true
runs:
  using: composite
  steps:
    - run: |
        state=$(gh issue view "$ISSUE_NUMBER" --json state -q .state)
        if [ "$state" = "CLOSED" ]; then
          gh issue reopen "$ISSUE_NUMBER" -c "CI failed. $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
        fi
      shell: bash
      if: failure()
      env:
        ISSUE_NUMBER: ${{inputs.issue_number}}
        GITHUB_TOKEN: ${{github.token}}
    - run: |
        gh issue close "$ISSUE_NUMBER"
      shell: bash
      env:
        ISSUE_NUMBER: ${{inputs.issue_number}}
        GITHUB_TOKEN: ${{github.token}}
